Implement strings API in test executor
zio/zio-redis pull request #511
Opened 2022-01-03 01:11 UTC by mvelimir

Resolves #198 
[BITFIELD](https://redis.io/commands/bitfield) not yet implemented

2022-01-05 18:53 UTC, jdegoes commented
Looks really great! Would be good to have some tests for the new operations to make sure they are working as specified.

2022-01-13 14:51 UTC, mijicd commented
@mvelimir Please resolve the conflicts.

2022-02-06 15:48 UTC, mijicd commented
@mvelimir Is this still work in progress? If not, please convert it to a pull request :)

2022-02-06 15:51 UTC, mvelimir commented
There's still the BITFIELD command left to be implemented, but I could make a separate PR for that.

2022-02-06 15:52 UTC, mijicd commented
@mvelimir I agree, let's have it in a separate PR. Please rebase this one, and I'll review it immediately.

2022-02-06 16:12 UTC, mijicd requested changes
First pass done.

2022-02-06 16:12 UTC, mijicd commented on redis/src/main/scala/zio/redis/TestExecutor.scala
> +                      .map(tuple => f"${tuple._1.asInstanceOf[Int].toBinaryString}%8s".replace(' ', '0') -> tuple._2)
Let's get rid of `asInstanceOf`.

2022-02-06 16:12 UTC, mijicd commented on redis/src/main/scala/zio/redis/TestExecutor.scala
> +                } else STM.succeed(Replies.Error)
Simplify as suggested above.

2022-02-06 16:12 UTC, mijicd commented on redis/src/main/scala/zio/redis/TestExecutor.scala
> +              }
Simplify as suggested above.

2022-02-06 16:12 UTC, mijicd commented on redis/src/main/scala/zio/redis/TestExecutor.scala
> +            }
Ditto.

2022-02-06 16:12 UTC, mijicd commented on redis/src/main/scala/zio/redis/TestExecutor.scala
> +            }
Ditto

2022-02-06 16:12 UTC, mijicd commented on redis/src/main/scala/zio/redis/TestExecutor.scala
> +                } else STM.succeed(Replies.Error)
You can use `ZSTM.cond`

2022-02-06 16:12 UTC, mijicd commented on redis/src/main/scala/zio/redis/TestExecutor.scala
> +              }
Simplify as suggested above.

2022-02-06 16:12 UTC, mijicd commented on redis/src/main/scala/zio/redis/TestExecutor.scala
> +                }
Simplify as suggested above.

2022-02-06 16:12 UTC, mijicd commented on redis/src/main/scala/zio/redis/TestExecutor.scala
> +              }
Simplify as suggested above.

2022-02-15 10:11 UTC, jdegoes commented
@mvelimir Would love to get this in! Do you have a chance to push it through?

2022-02-15 19:47 UTC, mvelimir commented
Sorry for the wait.

2022-02-16 06:26 UTC, mijicd approved these changes

2022-02-16 06:26 UTC, merged