Server api
zio/zio-redis pull request #529
Opened 2022-01-29 22:48 UTC by hcwilhelm

Please ignore ApiSpec and zio.package. I will fix them later when I am ready with the PR

2022-02-01 10:49 UTC, hcwilhelm commented
@mijicd were you able to take a look at this PR? I would like to know if I am on the right track before putting too much effort into it.

2022-02-02 08:30 UTC, mijicd reviewed
First pass done, looks great. I'll do a more thorough review once it's ready. Please specify the PR scope once it's ready for review, and don't forget to reference the issue :).

2022-02-02 08:30 UTC, mijicd commented on redis/src/main/scala/zio/redis/options/Server.scala
> +    case object Reset                                                         extends Rule
Let's seal the case classes.

2022-02-02 08:30 UTC, mijicd commented on redis/src/main/scala/zio/redis/options/Server.scala
> +    val NoCommands  = RemoveCommand("all")
Please make them final.

2022-02-02 08:30 UTC, mijicd commented on redis/src/main/scala/zio/redis/api/Server.scala
> +  final def aclCat(): ZIO[RedisExecutor, RedisError, Chunk[String]] = {
I would remove `()`. The same applies to all other no-arg functions.

2022-02-02 08:30 UTC, mijicd commented on redis/src/main/scala/zio/redis/Output.scala
> +          val commnads  = MultiStringOutput.unsafeDecode(values(5))
Probably a typo.

2022-02-02 08:30 UTC, mijicd commented on redis/src/main/scala/zio/redis/options/Server.scala
> +    passwords: List[String],
I'd use `Chunk` wherever is possible.

2022-02-02 08:30 UTC, mijicd commented on redis/src/test/scala/zio/redis/OutputSpec.scala
> +          val userEntryRaw = "user default on nopass ~* &* +@all"
I'd define it in for comprehension, lifted in UIO. The same applies to other occurrences.

2022-02-02 08:35 UTC, hcwilhelm commented
> First pass done, looks great. I'll do a more thorough review once it's ready. Please specify the PR scope once it's ready for review, and don't forget to reference the issue :).

@mijicd Thanks for your feedback I will address all your comments and continue implementing the server API commands

2022-02-20 17:09 UTC, anatolysergeev requested changes

2022-02-20 17:09 UTC, anatolysergeev commented on redis/src/main/scala/zio/redis/options/Server.scala
> +    step: Int,
I think, We have to stick with Long type everywhere, cause Redis integer is 64 bit in most cases, according to documentation [Resp Integer](https://redis.io/topics/protocol#resp-integers)

2023-09-06 06:58 UTC, closed without merging